### ISSUE TITLE
no TAP output with --close option?

### ISSUE THREAD

**Issue by mattdesl** [hughsk/smokestack#21]
Testing smokestack@2.0.0

The following works:
`browserify test/*.js | smokestack`

A browser window is opened and the TAP is printed to console. The window then remains open.

The following does not print anything to console and has an exit status of 1. No browser window shows up.

`browserify test/*.js | smokestack --close`

EDIT: Ok, seems like maybe I'm misunderstanding the usage. I guess I need a "close" command after all other tests have run? How could I go about doing that with multiple tests like in the above example? hmm..

**Comment by timoxley** [comment]
@mattdesl does this solve your problem?

**Comment by mattdesl** [comment]
Yep tap-closer works perfectly.
