### ISSUE TITLE
Sometimes not exiting

### ISSUE THREAD

**Issue by mattdesl** [hughsk/smokestack#44]
With recent versions of smokestack and/or tap-closer I've noticed the window is closing, but the process is not exiting so it hangs. I am running things locally at the moment. 

Will keep looking into it...

**Comment by joeybaker** [comment]
Happens every time for me with anything after smokestack 3.2

**Comment by joeybaker** [comment]
Nope, I'm wrong. The only pattern I really see is that it exits successfully once after a new smokestack install, then hangs on subsequent runs.

**Comment by joeybaker** [comment]
@mattdesl did you ever get anywhere on this?

**Comment by mattdesl** [comment]
nope, sadly

**Comment by joeybaker** [comment]
so… small progress: the problem doesn't happen if I use firefox. So, it's likely something in `chrome-launcher`

**Comment by joeybaker** [comment]
Seems to be related to chrome not exiting cleanly: https://code.google.com/p/chromium/issues/detail?id=338000

**Comment by tmcw** [comment]
Also running into this quite often in our testing stack

**Comment by joeybaker** [comment]
@tmcw FWIW, https://github.com/hughsk/chrome-launch/issues/2 fixed the issue for me.

**Comment by hughsk** [comment]
Apologies for the delay here all! This should be fixed in `smokestack@3.3.1` thanks to @joeybaker's patch, let me know if there are any further issues :)

**Comment by cdaringe** [comment]
hello. it hangs for me in both browsers :/ chrome & ff
