### ISSUE TITLE
stream.shutdown gets a number when run with firefox

### ISSUE THREAD

**Issue by tmcw** [hughsk/smokestack#50]
https://travis-ci.org/mapbox/canvas-linechart/builds/81631907#L292

This test seems to be failing because a stream emits a number as a status but smokestack expects it to be a callback function?

**Comment by tmcw** [comment]
Here's the test script: https://github.com/mapbox/canvas-linechart/blob/refactor/test/test.js

**Comment by hughsk** [comment]
Whoops — looks like this is being caused by a non-zero exit code getting passed through. On it :)

**Comment by hughsk** [comment]
@tmcw updated, would you be able to try again with `smokestack@3.4.1` and let me know if that fixes your issue? Thanks!

**Comment by tmcw** [comment]
:+1: 3.4.1 fixes the issue for me, thanks!
